services:
  database:
    image: 'mysql:latest'
    container_name: ldap_database_4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_ldap
    ports:
      - '3306'
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    container_name: ldap_phpmyadmin_4
    restart: always
    ports:
      - '8384:80'
    environment:
      PMA_HOST: database